steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/ens-metadata-service/cloud-run-source-deploy/rasterize', '.']
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/ens-metadata-service/cloud-run-source-deploy/rasterize']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'rasterize',
        '--image',
        'us-central1-docker.pkg.dev/ens-metadata-service/cloud-run-source-deploy/rasterize',
        '--region',
        'us-central1',
        '--no-traffic',
      ]
images:
  - us-central1-docker.pkg.dev/ens-metadata-service/cloud-run-source-deploy/rasterize
